# Generated by Django 4.2.7 on 2024-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="neighbors",
            field=models.ManyToManyField(blank=True, null=True, to="common.region"),
        ),
    ]
